CREATE TABLE kiado (
    nev VARCHAR2(100) NOT NULL,
    iranyitoszam NUMBER(4),
    varos VARCHAR2(50),
    utca VARCHAR2(100),
    hazszam VARCHAR2(10),
    CONSTRAINT KIADO_PRIMARY_KEY PRIMARY KEY (nev)
);

CREATE TABLE konyvek (
    ISBN NUMBER(10) NOT NULL,
    cim VARCHAR2(100),
    kiadas NUMBER(4),
    kiadonev VARCHAR2(100) NOT NULL,
    oldalszam NUMBER(5),
    kotes VARCHAR2(20),
    meret VARCHAR2(50),
    ar NUMBER(10),
    CONSTRAINT KONYVEK_FOREIGN_KEY FOREIGN KEY (kiadonev) REFERENCES kiado(nev),
    CONSTRAINT KONYVEK_PRIMARY_KEY PRIMARY KEY (ISBN)
);

CREATE TABLE szerzok (
    nev VARCHAR2(50) NOT NULL,
    ISBN NUMBER (10) NOT NULL,
    CONSTRAINT SZERZOK_FOREIGN_KEY FOREIGN KEY (ISBN) REFERENCES konyvek(ISBN),
    CONSTRAINT SZERZOK_PRIMARY_KEY PRIMARY KEY (nev, ISBN)
);

CREATE TABLE mufajok (
    mufaj VARCHAR2(50) NOT NULL,
    ISBN NUMBER (10) NOT NULL,
    CONSTRAINT MUFAJ_FOREIGN_KEY FOREIGN KEY (ISBN) REFERENCES konyvek(ISBN),
    CONSTRAINT MUFAJ_PRIMARY_KEY PRIMARY KEY (mufaj, ISBN)
);

CREATE TABLE sorozat (
    nev VARCHAR2(100) NOT NULL,
    ISBN NUMBER (10) NOT NULL,
    CONSTRAINT SOROZAT_FOREIGN_KEY FOREIGN KEY (ISBN) REFERENCES konyvek(ISBN),
    CONSTRAINT SOROZAT_PRIMARY_KEY PRIMARY KEY (nev, ISBN)
);

CREATE TABLE aruhazak (
    azonosito NUMBER(10) NOT NULL,
    iranyitoszam NUMBER(4),
    varos VARCHAR2(50),
    utca VARCHAR2(100),
    hazszam VARCHAR2(10),
    nev VARCHAR2(50),
    CONSTRAINT ARUHAZAK_PRIMARY_KEY PRIMARY KEY (azonosito)
);

CREATE TABLE raktaron (
    ISBN NUMBER (10) NOT NULL,
    azonosito NUMBER(10) NOT NULL,
    darabszam NUMBER(5),
    CONSTRAINT RAKTARON_FOREIGN_KEY_ISBN FOREIGN KEY (ISBN) REFERENCES konyvek(ISBN),
    CONSTRAINT RAKTARON_FOREIGN_KEY_AZONOSITO FOREIGN KEY (azonosito) REFERENCES aruhazak(azonosito),
    CONSTRAINT RAKTARON_PRIMARY_KEY PRIMARY KEY (ISBN, azonosito)
);

CREATE TABLE kuponok (
    kod VARCHAR2(10) NOT NULL,
    kedvezmeny NUMBER(3),
    mufaj VARCHAR(50) NOT NULL,
    --CONSTRAINT KUPONOK_FOREIGN_KEY FOREIGN KEY (mufaj) REFERENCES mufajok(mufaj),
    CONSTRAINT KUPONOK_PRIMARY_KEY PRIMARY KEY (kod)
);

CREATE TABLE felhasznalok (
    vezeteknev VARCHAR2(50),
    keresztnev VARCHAR2(50),
    jelszo VARCHAR2(100),
    email VARCHAR2(100) NOT NULL,
    iranyitoszam NUMBER(4),
    varos VARCHAR2(50),
    utca VARCHAR2(100),
    hazszam VARCHAR2(10),
    szuldatum DATE,
    admin NUMBER(1),
    CONSTRAINT FELHASZNALOK_PRIMARY_KEY PRIMARY KEY(email)
);

CREATE TABLE rendelesek (
    email VARCHAR2(100) NOT NULL,
    ISBN NUMBER(10) NOT NULL,
    darabszam NUMBER(5),
    atv_helyszin VARCHAR2(100),
    rendeles_ideje DATE,
    atvetel_ideje DATE,
    CONSTRAINT RENDELESEK_FOREIGN_KEY_EMAIL FOREIGN KEY (email) REFERENCES felhasznalok(email),
    CONSTRAINT RENDELESEK_FOREIGN_KEY_ISBN FOREIGN KEY (ISBN) REFERENCES konyvek(ISBN),
    CONSTRAINT RENDELESEK_PRIMARY_KEY PRIMARY KEY (email, ISBN, rendeles_ideje)
);




